### ISSUE TITLE
(Feature) Serve commands via network

### ISSUE THREAD

**Issue by mickeyl** [Ircama/ELM327-emulator#10]
Many ELM327-based OBD2 adapters work via WiFi. It would be cool to have the ELM327-emulator listen via a customizable port. That way it could serve as a testbed for OBD2 apps running on mobile clients which usually can't connect via serial port.

**Comment by Ircama** [comment]
This is doable in principle but takes some coding and testing work (at the moment this application only supports traditional pseudo-tty ports and we need to bridge an inet socket to the pty code to do that). Can you make an example of a mobile app and related TCP/IP port?

**Comment by mickeyl** [comment]
All apps that support WiFi-based ELM327 adapters connect via `192.168.0.10:35000` – there are tons in the respective iOS and Android app stores.

**Comment by Ircama** [comment]
@mickeyl , yes, obviously, thanks for making me remind of this method. I implemented a preliminary version of the program supporting TCP/IP via `-n` option.
