### ISSUE TITLE
ATZ response when using knockoff ELM327

### ISSUE THREAD

**Issue by noloader** [Ircama/ELM327-emulator#15]
Hi Everyone,

This emulator is great. I hope I am not splitting too many hairs here...

According to ELM Electronics's [ELM327 Data Sheet](https://www.elmelectronics.com/ic/elm327/) (p. 8), the identification string is supposed to be like the following.

```
ELM327 v2.3
```

Valid versions are 1.0, 1.0a, 1.1, 1.2, 1.2a, 1.3, 1.3a, 1.4, 1.4b, 2.0, 2.1, 2.2, and 2.3. Also see ELM Electronics [AT Commands by Version](https://www.elmelectronics.com/wp-content/uploads/2020/05/AT_Command_Table.pdf).

This is what I get when I run *ELM327-emulator* and the `ATZ` command (with echo ON):

```
Command:
ATZ

Hex dump:
41 54 5a 0d 0d 0d 45 4c 4d 33 32 37 20 76 31 2e 
35 0d 0d 3e 

ASCII dump:
ATZ


ELM327 v1.5

>
```

If you are seeing `ELM327 v1.5`, the `ELM327 v1.5` identification string is a dead giveaway that the controller is a knockoff since ELM Electronics did not produce a 1.5 revision.

Now here's the rub... The knockoff ELM327's ( `ELM327 v1.5`) add a spurious `0d fc` in response to an `ATZ`. Here's what it looks like when I query a knockoff [ELM327 OBD-II scanner](https://www.amazon.com/gp/product/B0897G6BMZ) from Amazon. Notice the extra `od fc` (with echo ON):

```
Command:
ATZ

Hex dump:
41 54 5a 0d fc 0d 0d 45 4c 4d 33 32 37 20 76 31 
2e 35 0d 0d 3e 

ASCII dump:
ATZ
�

ELM327 v1.5

>
```

I *think* the choices are:

1. Keep using `v1.5`, and add the spurious `od fc`
2. Use `v1.4b` and don't add the spurious `od fc`
3. Add an option like `-quirks` or `-knockoff` that controls when `od fc` is added.

**Comment by Ircama** [comment]
Added some arguments to the `version` command to change the version string and also the header.
`help version` to check the usage. See also the README.

Examples:

```
version ELM327 v2.3

version hexheader 0d fc 0d 0d
```
