### ISSUE TITLE
AT DP response when using ELM327-emulator

### ISSUE THREAD

**Issue by noloader** [Ircama/ELM327-emulator#16]
Hi Everyone,

This emulator is great. I hope I am not splitting too many hairs here...

According to ELM Electronics's [ELM327 Data Sheet](https://www.elmelectronics.com/ic/elm327/) (p. 18), the `AT DP` response displays `AUTO` when the ELM327 performed an automatic protocol search (i.e., connect with `AT SP 0`). In fact, I observe the behavior when using my knockoff [ELM327 OBD-II scanner](https://www.amazon.com/gp/product/B0897G6BMZ) from Amazon:

```
Command:
AT SP 0

Hex dump:
41 54 20 53 50 20 30 0d 4f 4b 0d 0d 3e 

ASCII dump:
AT SP 0
OK

>

Command:
AT DP

Hex dump:
41 54 20 44 50 0d 41 55 54 4f 0d 0d 3e 

ASCII dump:
AT DP
AUTO

>
```

This is what I observe when I run *ELM327-emulator*. Notice the `?` response instead of `AUTO` response:

```
Command:
AT SP 0

Hex dump:
4f 4b 0d 0d 3e 

ASCII dump:
OK

>

Command:
AT DP

Hex dump:
3f 20 0d 0d 3e 

ASCII dump:
? 

>
```

**Comment by Ircama** [comment]
This happened with `scenario car`, where a debug configuration was either returning '?' or 'AUTO, ISO 15765-4 (CAN 11/500)'.
I'm fixing it by providing the message '`AUTO, ISO 15765-4 (CAN 11/500) `' in case of 'AT SP 0' or 'AT SP 6'
