### ISSUE TITLE
CRITICAL:root:Error while opening 'COM3

### ISSUE THREAD

**Issue by unruledboy** [Ircama/ELM327-emulator#3]
Got it running on com0com on Windows 10, but after restarting, it now says:

> CRITICAL:root:Error while opening 'COM3':
> could not open port 'COM3': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
> 
> Cannot start ELM327-emulator.

Any idea? Thanks.

I tried to use other ports like COM4/COM5 still the same

**Comment by qqj1228** [comment]
You should build one serial port pair with COM3 and COM4，or rename the existed port pair to COM3 and COM4.
