### ISSUE TITLE
Connect escaner using Bluetooth

### ISSUE THREAD

**Issue by NickEsColR** [Ircama/ELM327-emulator#33]
Hi, thanks for all the efort in this emulator. I want to know how is posible to connect my phone to the emulator using bluetooth, i follow the steps in the readme file and create a port for bluetooth connection. I run the emulator using that port and succesfully test some commands using the CLI, but I can´t find any bluetooth device available to connect from my phone to test the application. 
¿Is there anything else to set up before running?
I run the command below
py -m elm -p COM8 -a 38400 -s car

**Comment by Ircama** [comment]
ELM327-emulator allows connecting smartphone applications via TCP/IP or through a Bluetooth COM port link. The procedure for setting this communication port with operating systems is beyond the scope of this program.
