### ISSUE TITLE
emulator starts at /dev/ttys000 on Mac OS Mojave

### ISSUE THREAD

**Issue by oleksandr-k** [Ircama/ELM327-emulator#5]
I'm using emulators as described and it starts at /dev/ttys000. I'm using connector for serial ports interaction and it can't find the device. Can I make somehow to start emulator at /dev/tty.XXX?

**Comment by Ircama** [comment]
Can you test this with python3?
```python
import pty
import os
master_fd, slave_fd = pty.openpty()
print("Running on", os.ttyname(slave_fd))
```

**Comment by oleksandr-k** [comment]
Hello @Ircama , thanks a lot for your attention, I'm sorry for bothering you, currently I avoid the problem by using another 3rd party for accessing to serial port on Mac.
I used ORSSerialPort library, it's good but it detects ports only on tty.xxx so I switched to SwiftSerial and it handles ttysXXX.

Thanks!
