### ISSUE TITLE
Proper response for unknown command

### ISSUE THREAD

**Issue by mickeyl** [Ircama/ELM327-emulator#8]
The _unknown command_ case is handled wrongly – a real ELM327 (and the behemoth of clones) answers with `?\r\r`, not just `\r` – the question mark is very important.

Reasoning: Said answer is very important, since it is good practice to start the ELM327 probing sequence by sending an invalid command, such as `.\r`, to ensure a consistent state of the send buffer – hence clients need to rely on a proper answer for _unknown command_.

**Comment by Ircama** [comment]
Software changed to manage the invalid answer message in `ELM_R_UNKNOWN`, which defaults to `?\r\r` and can be changed. Documentation updated accordingly.
